sudo: required
services:
-  docker
before_install: 
-  docker build -t jumgall/complex-client-test -f ./client/Dockerfile.dev ./client
script:
-  docker run -e CI=true jumgall/complex-client-test npm run test
after_success:
-  docker build -t jumgall/multi-client ./client
-  docker build -t jumgall/multi-nginx ./nginx
-  docker build -t jumgall/multi-server ./server
-  docker build -t jumgall/multi-worker ./worker

# deploy:
#   provider: 'elasticbeanstalk'
#   region: 'us-east-2'
#   app: 'docker-react-aws'
#   env: "Docker-react-aws-env"
#   bucket_name: elasticbeanstalk-us-east-2-664783549653
#   bucket_path: 'docker-react-aws'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"